### ISSUE TITLE
Cannot Load IOLVMPartitionScheme Kext -- Invalid Signature for org.catacombae.iokit.IOLVMPartitionScheme

### ISSUE THREAD

**Issue by jasonp019** [unsound/IOLVMPartitionScheme#1]
I'm trying to load the IOLVMPartitionScheme extension but I can't because the signature on the .kext is invalid.

Output of kextutil:

$ sudo kextutil -v 3 IOLVMPartitionScheme.kext
Defaulting to kernel file '/System/Library/Kernels/kernel'
Diagnostics for IOLVMPartitionScheme.kext:
Code Signing Failure: not code signed
IOLVMPartitionScheme.kext appears to be loadable (not including linkage for on-disk libraries).
Reading loaded kext info from kernel.
Untrusted kexts are not allowed
ERROR: invalid signature for org.catacombae.iokit.IOLVMPartitionScheme, will not load

With -v 6:

$ sudo kextutil -v 6 IOLVMPartitionScheme.kext
Kext user-space log filter changed from 0xff2 to 0xfff.
Kext kernel-space log filter changed from 0xff2 to 0xfff.
Kext library architecture set to x86_64.
Can't stat /AppleInternal - No such file or directory.
Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext library recording diagnostics for: validation authentication dependencies warnings.
Diagnostics for IOLVMPartitionScheme.kext:
Code Signing Failure: not code signed
IOLVMPartitionScheme.kext appears to be loadable (not including linkage for on-disk libraries).
Reading loaded kext info from kernel.
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received 'Get Loaded Kext Info' request from user space.
(kernel) Returning loaded kext info.
Loaded kext info:
{
}

Untrusted kexts are not allowed
ERROR: invalid signature for org.catacombae.iokit.IOLVMPartitionScheme, will not load

Thank you!

**Comment by GabLeRoux** [comment]
I don't know if it'll work, but you may have a look at these two links to install kext:
http://osxdaily.com/2012/01/12/how-to-manually-install-kernel-extensions-in-mac-os-x/
http://osxdaily.com/2012/01/04/install-kext-files-easily-with-kext-drop/

I haven't tried the kext from current repo and I wish there was some documentation or a readme for the project, but here's a related blog post for the project itself:
http://catacombae.blogspot.ca/2014/04/iolvmpartitionscheme-using-simple-linux.html

Good luck

**Comment by eduncan911** [comment]
@jasonp019 thanks for outlining what to actually run to get this kext loaded (there is zero README support here).

Thanks @GabLeRoux for the links. They didn't work for Sierra though.

However, after some time on the interwebs, I ran across this:

https://apple.stackexchange.com/questions/256138/trying-to-set-boot-args-with-nvram-gets-general-error-on-sierra

The solution is to reboot into recovery (CMD-R) and disabling Signing with:

    csrutil enable --without kext

After rebooting and disabling Signing, I successfully installed this kext module:

```
$ sudo kextutil -v 3 IOLVMPartitionScheme.kext
Password:
Defaulting to kernel file '/System/Library/Kernels/kernel'
Diagnostics for IOLVMPartitionScheme.kext:
Code Signing Failure: not code signed
IOLVMPartitionScheme.kext appears to be loadable (not including linkage for on-disk libraries).
Reading loaded kext info from kernel.
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "IOLVMPartitionScheme.kext"
kext signature failure override allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "/Users/eric/Downloads/IOLVMPartitionScheme-2014.11.15/IOLVMPartitionScheme.kext"
Reading loaded kext info from kernel.
Loading IOLVMPartitionScheme.kext.
Reading load info for 8 kexts.
Reading loaded kext info from kernel.
Adding /Users/eric/Downloads/IOLVMPartitionScheme-2014.11.15/IOLVMPartitionScheme.kext to mkext.
Created mkext for architecture x86_64 containing 1 kexts.
Loading IOLVMPartitionScheme.kext.
(kernel) Received request from user space to load kext org.catacombae.iokit.IOLVMPartitionScheme.
(kernel) Recorded kext org.catacombae.iokit.IOLVMPartitionScheme as a candidate for inclusion in prelinked kernel.
(kernel) Loading kext org.catacombae.iokit.IOLVMPartitionScheme.
(kernel) Allocated link buffer for kext org.catacombae.iokit.IOLVMPartitionScheme at 0xffffff7f87f83000 (69632 bytes).
(kernel) Kext org.catacombae.iokit.IOLVMPartitionScheme executable loaded; 17 pages at 0xffffff7f83983000 (load tag 158).
(kernel) Kext org.catacombae.iokit.IOLVMPartitionScheme has IOService subclass IOLVMPartitionScheme; enabling autounload.
(kernel) Kext org.catacombae.iokit.IOLVMPartitionScheme is now started.
(kernel) Kext org.catacombae.iokit.IOLVMPartitionScheme sending 1 personality to the IOCatalogue and starting matching.
(kernel) Kext org.catacombae.iokit.IOLVMPartitionScheme loaded.
Successfully loaded IOLVMPartitionScheme.kext.
IOLVMPartitionScheme.kext successfully loaded (or already loaded).
```

Now, to figure out how to use it once it is installed...  I have `fuse-ext2` installed (another PITA requiring a full Xcode install!).

**Comment by eduncan911** [comment]
Argh, didn't seem to work for me and the single HDD I am attempting to recover.

```
$ diskutil list /dev/disk2
/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *80.0 GB    disk2
   1:                      Linux                         209.7 MB   disk2s1
   2:       LVM_partition_scheme                         79.8 GB    disk2s2

$ kextstat | grep -v com.apple
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
...
  142    0 0xffffff7f838de000 0xc000     0xc000     org.catacombae.iokit.IOLVMPartitionScheme (2014.11.15) 9DFC72A0-DB2D-0324-99D8-31574EA4CA67 <16 5 4 3>
```

Still only lists the single LVM partition.

**Comment by unsound** [comment]
I have updated the [release](https://github.com/unsound/IOLVMPartitionScheme/releases) with a signed kext (thanks to [Tuxera Inc.](https://tuxera.com), my employer). This should fix the invalid signature issue.

@eduncan911 Please open a new issue if you still have the problem (it's probably unrelated to this issue), and always include 'dmesg' output in the report. In addition you could run the LVMTest binary on the device to gather useful debug info.
